include:
- project: iiidevops-templates/ci-template
  ref: v2.8.0
  file: ci/template.gitlab-ci.yml
- project: iiidevops-templates/ci-template
  ref: v2.8.0
  file: job/DeployDatabase.gitlab-ci.yml

stages:
- initial
- scan
- build
- deploy
- test

Deploy--Database:
  variables:
    iiidevops: deploy-db
    CHART_DB_GUI: "true"
    CHART_DB_NAME: "todo_db"
    CHART_DB_USERNAME: "iiidevops"
    CHART_DB_PASSWORD: "DevOps_123"
    CHART_DB_TAG: "4.4-debian-10"
    CHART_DB_TYPE: "mongodb"
    CHART_VOLUME_ENABLED: 'false'

Deploy--Wait DB deployment:
  variables:
    iiidevops: deploy-db
    max_wait: 128
  